Fixing Errors
Fixed: Bot taking gases at unfinished expansion as it counted as saturated due to 0/0 drones being employed there
Fixed: Error messages in console as bot tried to attack air units (overlords, overseers) with roaches

New error (only happens sometimes):
ERROR:sc2.protocol:Cannot receive: Connection already closed.
Traceback (most recent call last):
  File "C:\Users\naomi\AppData\Roaming\Python\Python37\site-packages\sc2\protocol.py", line 34, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\naomi\AppData\Roaming\Python\Python37\site-packages\aiohttp\client_ws.py", line 254, in receive_bytes
    msg.data))
TypeError: Received message 257:None is not bytes